#!/bin/bash
mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom
# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
# I want to sync aex source!
repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-10.0 -g default,-device,-mips,-darwin,-notdefault 
repo sync -j7 --force-sync

repo sync

repo sync

# Clone local manifest! So that no need to manually git clone repos or change hals, you can use normal git clone or rm and re clone, they will cost little more time, and you may get timeout! Let's make it quit and depth=1 too.
# My local manifest can do all clone, and removing or changing repository i need, so lets use it! I am lazy to manually git
https://github.com/Brock5555/twrp_device_xiaomi_violet.git -b android-10 device/xiaomi/violet

rm -rf out
# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -
